// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMlNcNQVzsknPT9VKaBvtINtibHixI37o',
    appId: '1:389293545672:web:56c755b924e8dd712c6dfd',
    messagingSenderId: '389293545672',
    projectId: 'musaic-84a4e',
    authDomain: 'musaic-84a4e.firebaseapp.com',
    storageBucket: 'musaic-84a4e.firebasestorage.app',
    measurementId: 'G-SY0R72VVPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6byfld3QvRf6Gu_rOUXiI5aDcZeIGtYI',
    appId: '1:389293545672:android:c3599f01302b09e72c6dfd',
    messagingSenderId: '389293545672',
    projectId: 'musaic-84a4e',
    storageBucket: 'musaic-84a4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5YQS1K6u_ar5YUM_qK5P2R1HJSeAIvqo',
    appId: '1:389293545672:ios:51f679798d06a3ad2c6dfd',
    messagingSenderId: '389293545672',
    projectId: 'musaic-84a4e',
    storageBucket: 'musaic-84a4e.firebasestorage.app',
    iosBundleId: 'com.apurv.musaic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5YQS1K6u_ar5YUM_qK5P2R1HJSeAIvqo',
    appId: '1:389293545672:ios:9b32b840d205d0072c6dfd',
    messagingSenderId: '389293545672',
    projectId: 'musaic-84a4e',
    storageBucket: 'musaic-84a4e.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMlNcNQVzsknPT9VKaBvtINtibHixI37o',
    appId: '1:389293545672:web:aca67626cdf04d182c6dfd',
    messagingSenderId: '389293545672',
    projectId: 'musaic-84a4e',
    authDomain: 'musaic-84a4e.firebaseapp.com',
    storageBucket: 'musaic-84a4e.firebasestorage.app',
    measurementId: 'G-G74VLVQBJ1',
  );
}
